print('='*10, 'Desafio 22', '='*10)
nome = str(input('Digite seu nome completo:')).strip()
maisculo = nome.upper()
minusculo = nome.lower()
print('O seu nome em maisculo é {}.'.format(maisculo))
print('O seu nome em minusculo é {}.'.format(minusculo))
aotodo = len(nome) - nome.count(' ')
print('O seu nome ao todo tem {} letras.'.format(aotodo))
primeiro = nome.split()
print('O seu primeiro nome é {} e ele tem {} letras.'.format(primeiro[0],len(primeiro[0])))
print('='*10, 'Desafio 22', '='*10)
